# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "1b:f0:c8:36:a9:5f:4a:bf:6f:84:dc:18:aa:8c:33:e5"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # resore temp from previous stored
      - restore_cache:
          keys:
          - v1-tmp-{{ checksum "seed" }}
        #   - v1-tmp-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run fetch
      - run: yarn run fetch

      # set committer
      - run: git config --global user.email "CircleCI@CircleCI.com"
      - run: git config --global user.name "CircleCI"

      # store cache on .tmp
      - save_cache:
          paths:
            - .tmp
          key: v1-tmp-{{ checksum "seed" }}

      - run: 
          command: if [[ `git status --porcelain` ]]; then git add -A && git commit -m "$(tail -n 1 message)" && git push origin HEAD:master; fi;
          name: push changes
      - run: 
          command: if [[ $(tail -n 1 message) = *"finished the job for"* ]]; then yarn run generate && yarn run deploy; fi;
          name: deploy

workflows:
  version: 2
  commit:
    jobs:
      - build
  build-deploy:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build